server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: hubspot-integration-api
  datasource:
    url: jdbc:h2:mem:hubspotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      enabled: true
    version: 1.0.0
    title: HubSpot Integration API
    description: API que faz integração com o HubSpot

hubspot:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URL}/auth/callback
  auth-url: ${AUTH_URL}
  token-url: ${TOKEN_URL}
  authorization-grant-type: authorization_code
  scopes: crm.objects.contacts.read crm.objects.contacts.write crm.schemas.contacts.read crm.schemas.contacts.write
  api:
    base-url: ${BASE_URL}
    create-contact: /crm/v3/objects/contacts

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web.servlet.DispatcherServlet: ERROR

security:
  ignored: /h2-console/**,/swagger-ui/**,/v3/api-docs/**,/v3/api-docs.yaml,/swagger-resources/**,/webjars/**
  permit-all: /**

resilience4j:
  ratelimiter:
    instances:
      hubspot-rate-limit:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 0

