spring:
  application:
    name: hubspot-integration-api
  datasource:
    url: jdbc:h2:mem:hubspotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    whitelabel:
      enabled: false

hubspot:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URL}/api/hubspot/callback
  auth-url: ${AUTH_URL}
  token-url: ${TOKEN_URL}
  authorization-grant-type: authorization_code
  scopes: crm.objects.contacts.read crm.objects.contacts.write crm.schemas.contacts.read crm.schemas.contacts.write

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web.servlet.DispatcherServlet: ERROR

security:
  ignored: /h2-console/**
  permit-all: /**
